name: Code Quality with Ruff

on:
  push:
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Ruff
      run: |
        pip install ruff
        echo "Ruff installed successfully"
      
    - name: Run Ruff linter
      run: |
        echo "Running ruff check..."
        ruff check . || echo "Linting issues found"
        echo "Ruff check completed"
      
    - name: Check formatting with Ruff
      run: |
        echo "Checking formatting..."
        ruff format --check --diff . || echo "Formatting issues found"
        echo "Format check completed"
      continue-on-error: true
      
    - name: Apply fixes and formatting (push only)
      if: github.event_name == 'push'
      run: |
        echo "Applying Ruff fixes and formatting..."
        ruff check --fix .
        ruff format .
        echo "Fixes and formatting applied"
        
    - name: Check for changes and commit (push only)
      if: github.event_name == 'push'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Check if there are any changes
        if [[ -n $(git status --porcelain) ]]; then
          echo "Changes detected, committing..."
          
          # Get the previous commit message
          PREV_COMMIT_MSG=$(git log -1 --pretty=%B)
          NEW_COMMIT_MSG="${PREV_COMMIT_MSG} [ruff fix/format]"
          
          git add -A
          git commit -m "$NEW_COMMIT_MSG"
          git push
          echo "Changes committed and pushed with message: $NEW_COMMIT_MSG"
        else
          echo "No changes to commit"
        fi
